
-- Ensure public.users table exists with correct structure
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  password TEXT,
  role TEXT NOT NULL DEFAULT 'customer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policies for public.users
DROP POLICY IF EXISTS "Users view own profile" ON public.users;
CREATE POLICY "Users view own profile" ON public.users FOR SELECT USING (
  email = (auth.jwt() ->> 'email')
);

DROP POLICY IF EXISTS "Users update own profile" ON public.users;
CREATE POLICY "Users update own profile" ON public.users FOR UPDATE USING (
  email = (auth.jwt() ->> 'email')
);

DROP POLICY IF EXISTS "Admins view all profiles" ON public.users;
CREATE POLICY "Admins view all profiles" ON public.users FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.users u 
    WHERE u.email = (auth.jwt() ->> 'email') 
    AND u.role = 'admin'
  )
);

-- Trigger function to sync auth.users to public.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _full_name TEXT;
  _phone TEXT;
BEGIN
  _full_name := COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1));
  _phone := NEW.raw_user_meta_data->>'phone';

  INSERT INTO public.users (full_name, email, phone, role)
  VALUES (_full_name, NEW.email, _phone, 'customer')
  ON CONFLICT (email) DO UPDATE 
  SET full_name = EXCLUDED.full_name,
      phone = COALESCE(public.users.phone, EXCLUDED.phone);
      
  RETURN NEW;
END;
$$;

-- Recreate trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created 
  AFTER INSERT ON auth.users 
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Backfill existing users from auth.users to public.users
INSERT INTO public.users (full_name, email, role)
SELECT 
  COALESCE(raw_user_meta_data->>'full_name', split_part(email, '@', 1)),
  email,
  'customer'
FROM auth.users
ON CONFLICT (email) DO NOTHING;
